USE arithmo_app;

CREATE TABLE users(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(180) NOT NULL UNIQUE,
name VARCHAR (100) NOT NULL,
lastName VARCHAR (100) NOT NULL,
image VARCHAR(255) NULL, 
password VARCHAR(90) NOT NULL,
create_at TIMESTAMP(0) NOT NULL,
update_at TIMESTAMP(0) NOT NULL,
edad VARCHAR(100) NOT NULL
);


CREATE TABLE scores (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    score INT NOT NULL,
    created_at TIMESTAMP (0) NOT NULL,
    update_at TIMESTAMP(0) NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);  



